[package]
name = "mintNft"
version = "1.0.0"
authors = []

[addresses]
mint_nft = '_'
aptos_framework = "0x1"
aptos_token = "0x3"
admin_addr = '0xf5d47de146c9c41f6a19a0d44ce549f5ee0f8b67594bd80e4689e8aefc34da9d'

[dev-addresses]
mint_nft = '0x2'


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
