[package]
name = "basicCoinFull"
version = "1.0.0"
authors = []

[addresses]
named_addr = '0x33833308a1256a6def08436d2a9ce9c927681b734ba48ccc75ec8722f1886793'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
